version: "3.8"

services:
  api:
    build:
      target: builder
    ports:
      - 5000:5000
    networks:
      - api-network
    environment:
      - API_PORT=5000
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=tasks-python
      - CLIENT_URI=http://localhost:3000
    volumes:
      - ./api/tasks:/app/api/tasks
    command: uvicorn api.tasks.main:app --reload --port 5000 --host 0.0.0.0 --log-level=info

  mongodb:
    image: mongo:4.0
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    networks:
      - api-network

networks:
  api-network:
volumes:
  db:
